package cl.cardif.service.ebsc.aachcarclaiminformation.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2021-07-29T12:41:18.055-04:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://cardif.cl/Service/EBSC/AACHCarClaimInformation/v1", name = "AACHCarClaimInformationPortType")
@XmlSeeAlso({cl.cardif.schema.eso.error.v1.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, cl.cardif.schema.eso.dictionary.v1.ObjectFactory.class, cl.cardif.schema.eso.messageheader.v1.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, cl.cardif.schema.eso.result.v1.ObjectFactory.class, cl.cardif.schema.ebm.aachcarclaiminformation.get.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AACHCarClaimInformationPortType {

    @WebMethod(action = "http://cardif.cl/EBS/AACHCarClaimInformation/get")
    @WebResult(name = "get_AACHCarClaimInformation_RSP", targetNamespace = "http://cardif.cl/Schema/EBM/AACHCarClaimInformation/get/v1.0", partName = "Out")
    public cl.cardif.schema.ebm.aachcarclaiminformation.get.v1.GetAACHCarClaimInformationRSPType getList(
        @WebParam(partName = "In", name = "get_AACHCarClaimInformation_REQ", targetNamespace = "http://cardif.cl/Schema/EBM/AACHCarClaimInformation/get/v1.0")
        cl.cardif.schema.ebm.aachcarclaiminformation.get.v1.GetAACHCarClaimInformationREQType in
    ) throws GetFaultMessage;
}
