package cl.cardif.service.ebsc.aachcarclaiminformation.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2021-07-29T14:19:18.370-04:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "AACHCarClaimInformationService", 
                  wsdlLocation = "classpath:wsdl/AACHCarClaimInformation.wsdl",
                  targetNamespace = "http://cardif.cl/Service/EBSC/AACHCarClaimInformation/v1") 
public class AACHCarClaimInformationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cardif.cl/Service/EBSC/AACHCarClaimInformation/v1", "AACHCarClaimInformationService");
    public final static QName AACHCarClaimInformationPort = new QName("http://cardif.cl/Service/EBSC/AACHCarClaimInformation/v1", "AACHCarClaimInformationPort");
    static {
        URL url = AACHCarClaimInformationService.class.getClassLoader().getResource("wsdl/AACHCarClaimInformation.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(AACHCarClaimInformationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/AACHCarClaimInformation.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public AACHCarClaimInformationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AACHCarClaimInformationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AACHCarClaimInformationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AACHCarClaimInformationPortType
     */
    @WebEndpoint(name = "AACHCarClaimInformationPort")
    public AACHCarClaimInformationPortType getAACHCarClaimInformationPort() {
        return super.getPort(AACHCarClaimInformationPort, AACHCarClaimInformationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AACHCarClaimInformationPortType
     */
    @WebEndpoint(name = "AACHCarClaimInformationPort")
    public AACHCarClaimInformationPortType getAACHCarClaimInformationPort(WebServiceFeature... features) {
        return super.getPort(AACHCarClaimInformationPort, AACHCarClaimInformationPortType.class, features);
    }

}
