
package cl.cardif.service.ebsc.usuario.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2021-07-29T12:41:18.331-04:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "autenticar_Usuario_FRSP", targetNamespace = "http://cardif.cl/Schema/EBM/Usuario/autenticar/v1.0")
public class AutenticarFaultMessage extends Exception {
    
    private cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioFRSPType autenticarUsuarioFRSP;

    public AutenticarFaultMessage() {
        super();
    }
    
    public AutenticarFaultMessage(String message) {
        super(message);
    }
    
    public AutenticarFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public AutenticarFaultMessage(String message, cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioFRSPType autenticarUsuarioFRSP) {
        super(message);
        this.autenticarUsuarioFRSP = autenticarUsuarioFRSP;
    }

    public AutenticarFaultMessage(String message, cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioFRSPType autenticarUsuarioFRSP, Throwable cause) {
        super(message, cause);
        this.autenticarUsuarioFRSP = autenticarUsuarioFRSP;
    }

    public cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioFRSPType getFaultInfo() {
        return this.autenticarUsuarioFRSP;
    }
}
