package cl.cardif.service.ebsc.usuario.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Servicio SOAP 1.2 que define la autenticación de un usuario mediante dominio, usuario y contraseña
 *         
 *
 * This class was generated by Apache CXF 3.0.1
 * 2021-07-29T14:19:18.505-04:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "UsuarioService", 
                  wsdlLocation = "file:/C:/Users/diego/Documents/GitHub/variosCardif/wsCotizador/wsCotizadorBusiness/src/main/resources/wsdl/wsdl_authentication.wsdl",
                  targetNamespace = "http://cardif.cl/Service/EBSC/Usuario/v1") 
public class UsuarioService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cardif.cl/Service/EBSC/Usuario/v1", "UsuarioService");
    public final static QName UsuarioPort = new QName("http://cardif.cl/Service/EBSC/Usuario/v1", "UsuarioPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/diego/Documents/GitHub/variosCardif/wsCotizador/wsCotizadorBusiness/src/main/resources/wsdl/wsdl_authentication.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UsuarioService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/diego/Documents/GitHub/variosCardif/wsCotizador/wsCotizadorBusiness/src/main/resources/wsdl/wsdl_authentication.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UsuarioService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuarioService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns UsuarioPortType
     */
    @WebEndpoint(name = "UsuarioPort")
    public UsuarioPortType getUsuarioPort() {
        return super.getPort(UsuarioPort, UsuarioPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuarioPortType
     */
    @WebEndpoint(name = "UsuarioPort")
    public UsuarioPortType getUsuarioPort(WebServiceFeature... features) {
        return super.getPort(UsuarioPort, UsuarioPortType.class, features);
    }

}
