package cl.cardif.service.ebsc.usuario.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Port que define la estructura del servicio, cuenta con una sola operación 'autenticar'
 *         
 *
 * This class was generated by Apache CXF 3.0.1
 * 2021-07-29T14:19:18.499-04:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://cardif.cl/Service/EBSC/Usuario/v1", name = "UsuarioPortType")
@XmlSeeAlso({cl.cardif.schema.ebm.usuario.autenticar.v1.ObjectFactory.class, cl.cardif.schema.eso.error.v1.ObjectFactory.class, cl.cardif.schema.eso.dictionary.v1.ObjectFactory.class, cl.cardif.schema.eso.messageheader.v1.ObjectFactory.class, cl.cardif.schema.eso.result.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UsuarioPortType {

    @WebMethod(action = "http://cardif.cl/EBS/Usuario/autenticar")
    @WebResult(name = "autenticar_Usuario_RSP", targetNamespace = "http://cardif.cl/Schema/EBM/Usuario/autenticar/v1.0", partName = "Out")
    public cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioRSPType autenticar(
        @WebParam(partName = "In", name = "autenticar_Usuario_REQ", targetNamespace = "http://cardif.cl/Schema/EBM/Usuario/autenticar/v1.0")
        cl.cardif.schema.ebm.usuario.autenticar.v1.AutenticarUsuarioREQType in
    ) throws AutenticarFaultMessage;
}
